apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: superapi-dev

commonLabels:
  environment: dev

namePrefix: dev-

resources:
- ../../base
- namespace.yaml
  
replicas:
- count: 2
  name: superapi

images:
- name: ghcr.io/gbaeke/super
  newName: ghcr.io/gbaeke/super
  newTag: "1.0.2"
